"""empty message

Revision ID: 068763840087
Revises: 719301a13ccf
Create Date: 2020-05-21 22:22:38.247458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '068763840087'
down_revision = '719301a13ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed', sa.Column('primary_names_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('fk__parsed__primary_names__names', 'parsed', type_='foreignkey')
    op.create_foreign_key(op.f('fk__parsed__primary_names_uuid__names'), 'parsed', 'names', ['primary_names_uuid'], ['local_uuid'])
    op.drop_column('parsed', 'primary_names')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed', sa.Column('primary_names', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk__parsed__primary_names_uuid__names'), 'parsed', type_='foreignkey')
    op.create_foreign_key('fk__parsed__primary_names__names', 'parsed', 'names', ['primary_names'], ['local_uuid'])
    op.drop_column('parsed', 'primary_names_uuid')
    # ### end Alembic commands ###
