"""empty message

Revision ID: 719301a13ccf
Revises: 
Create Date: 2020-05-21 22:21:31.932304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '719301a13ccf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('local_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', 'local_uuid', name=op.f('pk__names')),
    sa.UniqueConstraint('local_uuid', name=op.f('uq__names__local_uuid'))
    )
    op.create_table('parsed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('data_publish', sa.DateTime(), nullable=True),
    sa.Column('is_annuled', sa.Boolean(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('publisher_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('publisher_type', sa.String(), nullable=False),
    sa.Column('bankrupt_name', sa.String(), nullable=False),
    sa.Column('is_refuted', sa.Boolean(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('primary_names', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['primary_names'], ['names.local_uuid'], name=op.f('fk__parsed__primary_names__names')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__parsed')),
    sa.UniqueConstraint('data_publish', name=op.f('uq__parsed__data_publish'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parsed')
    op.drop_table('names')
    # ### end Alembic commands ###
